defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

root_dir: . # Change to your project directory
size: [360,640] # Input image size [H,W]. Image will be resized to this size before feeding to the model

hyperparameter_optimization: false  # Set to True to run hyperparameter optimization
train_model: false # Set to True to train the model
dataset:
  root: ${root_dir}\data # Change to your data directory
  size: ${size}
  print_summary: false
train_transforms:
  # Parameters for random data augmentation during training
  rotation: 1
  brightness: 0.13421751726418732
  contrast: 0.004651633836328983
  saturation: 0.17556343339383604
  hue: 0.046270601078867914
  random_gray_scale: 0.09155612904578447
train:
  train_batch_size: 16
  val_batch_size: 32
  num_workers: 4 # Number of workers for data loading
  log_dir: ${root_dir}\logs # Directory to save logs
  save_model_dir: ${root_dir}\models  # Directory to save model checkpoints
  enable_progress_bar: true
  monitor: val_loss  # Metric to monitor for early stopping.
  trainer:
    max_epochs: 100
    log_every_n_steps: 5
model:
  lr: 0.00044385329608533753
  weight_decay: 0.07105427971339849
  model_name: resnet50 # Model name. Valid values are resnet18, resnet34, resnet50
  patience: 8  # Number of epochs to wait before reducing learning rate. And 2*number of epochs to wait before early stopping
  reduce_factor: 0.24675830426811984 # Factor by which learning rate will be reduced
  train_n_layers: 1 # Number of hidden layers to train. 0 means train only classification layer
  dropout_rate: 0.19791567102074625
run:
  sound_path: ${root_dir}/assets/sound.mp3 # Path to sound file to be played when bad posture is detected. Supported formats are mp3 and wav. If none is provided, no sound will be played
  size: ${size}
  model_path: ${root_dir}/models/resnet50.ckpt  # Path to model checkpoint
  time_span: 30 # Time span in seconds for which the posture should be bad to trigger an alert
  min_samples: 100 # Minimum number of samples in the time span for which the posture should be bad to trigger an alert
  show: true # Set to True to show the video feed
  camera_index: 0 # Index of the camera to use. 0 means use the default camera
  sleep_time: 0 # Time in seconds to sleep between each frame. Set to 0 to disable. This is useful when running on CPU
  device: auto  # Device to use. Valid values are auto, cpu, cuda, mps.
