defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

root_dir: . # Change to your project directory
size: [360,640] # Input image size [H,W]. Image will be resized to this size before feeding to the model

hyperparameter_optimization: false  # Set to True to run hyperparameter optimization
train_model: false # Set to True to train the model
dataset:
  root: ${root_dir}\data # Change to your data directory
  size: ${size}
  print_summary: false
train_transforms:
  # Parameters for random data augmentation during training
  brightness:  0.11388021369311191
  contrast: 0.05647132194565846
  saturation: 0.08707688195327586
  hue: 0.14190822706036743
  random_gray_scale: 0.10354352211071055
train:
  train_batch_size: 32
  val_batch_size: 64
  num_workers: 8 # Number of workers for data loading
  log_dir: ${root_dir}\logs # Directory to save logs
  save_model_dir: ${root_dir}\models  # Directory to save model checkpoints
  enable_progress_bar: true
  monitor: val_loss  # Metric to monitor for early stopping.
  patience: 5  # Number of epochs to wait for early stopping
  trainer:
    max_epochs: 100
    log_every_n_steps: 5
model:
  lr: 0.00032114631562197345
  weight_decay: 0.0001032884773774556
  model_name: resnet34 # Model name. Valid values are resnet18, resnet34, resnet50
  dropout_rate: 0.32632336954383523
run:
  size: ${size}
  model_path: ${root_dir}/models/resnet34.ckpt  # Path to model checkpoint
  time_span: 30 # Time span in seconds for which the posture should be bad to trigger an alert
  min_samples: 100 # Minimum number of samples in the time span for which the posture should be bad to trigger an alert
  show: true # Set to True to show the video feed
  camera_index: 0 # Index of the camera to use. 0 means use the default camera
  sleep_time: 0 # Time in seconds to sleep between each frame. Set to 0 to disable. This is useful when running on CPU
  device: auto  # Device to use. Valid values are auto, cpu, cuda, mps.
  explain: False # Set to True to show the explanation for the prediction