defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

root_dir : . # Change to your project directory
size: [360,640 ] # Input image size [H,W]. Image will be resized to this size before feeding to the model
hyperparameter_optimization: False # Set to True to run hyperparameter optimization
train_model: False # Set to True to train the model


dataset:
  root: ${root_dir}\data # Change to your data directory
  size: ${size}
  print_summary: False # Set to True to print dataset summary

train_transforms:
  # Parameters for random data augmentation during training
  rotation: 0
  brightness: 0.12
  contrast: 0.175
  saturation: 0.1
  hue: 0.15
  random_gray_scale: 0.05

train:
  # Parameters for training
  train_batch_size: 16 #
  val_batch_size: 32
  num_workers: 4 # Number of workers for data loading
  log_dir: ${root_dir}\logs # Directory to save logs
  save_model_dir: ${root_dir}\models # Directory to save model checkpoints
  enable_progress_bar: True
  monitor: val_loss # Metric to monitor for early stopping. Valid values are val_loss, val_acc, val_f1
  trainer:
    max_epochs: 100
    log_every_n_steps: 5

model:
  lr : 0.0005
  weight_decay: 1e-5 #
  model_name: resnet18 # Model name. Valid values are resnet18, resnet34, resnet50
  patience: 5 # Number of epochs to wait before reducing learning rate. And 2*number of epochs to wait before early stopping
  reduce_factor: 0.5 # Factor by which learning rate will be reduced
  train_n_layers: 1 # Number of convolutional blocks to train. 0 means train only classification layer

run:
  sound_path : ${root_dir}/assets/sound.mp3 # Path to sound file to be played when bad posture is detected. Supported formats are mp3 and wav. If none is provided, no sound will be played
  size: ${size}
  model_path: ${root_dir}/models/model.ckpt # Path to model checkpoint
  time_span: 30 # Time span in seconds for which the posture should be bad to trigger an alert
  min_samples: 100 # Minimum number of samples in the time span for which the posture should be bad to trigger an alert
  show: True # Set to True to show the video feed
  camera_index: 0 # Index of the camera to use. 0 means use the default camera
  explain: False # Set to True to show the heatmap produced by EigenCAM
  sleep_time: 0 # Time in seconds to sleep between each frame. Set to 0 to disable. This is useful when running on CPU